name: familybot

services:
  familybot:
    build: '.'
    container_name: familybot
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      - DEBUG
      - TZ=Europe/Helsinki
      - TELEGRAM_GROUP
      - TELEGRAM_ALLOWEDUSERNAMES
      - TELEGRAM_TOKEN
      - WEATHERAPI_KEY
      - CURRENCYAPI_KEY
      - OPENAIAPI_KEY
      - OPENAIAPI_GPTMODEL=gpt-4o
      - MINIFLUXAPI_KEY
      - MINIFLUXAPI_BASEURL=https://miniflux.rahfar.com
      - MINIFLUXAPI_SITEURL=https://www.nytimes.com
      - DEEPLAPI_KEY
      - REDIS_ADDR=redis:6379
      - ANTHROPICAPI_KEY
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: 'redis:6'
    container_name: redis
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
