name: familybot

services:
  familybot:
    build: '.'
    container_name: familybot
    ports:
      - '127.0.0.1:8080:8080'
    labels:
      - conf_version=1
    environment:
      - DEBUG
      - TZ=Europe/Helsinki
      - TG_GROUPID
      - TG_ADMINUSERIDS
      - TG_TOKEN
      - WEATHERAPI_KEY
      - CURRENCYAPI_KEY
      - OPENAIAPI_KEY
      - DEEPLAPI_KEY
      - MINIFLUXAPI_KEY
      - MINIFLUXAPI_BASEURL=https://miniflux.rahfar.com
      - REDIS_ADDR=redis:6379
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: 'redis:6'
    container_name: redis
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
