name: build and deploy

on:
  push:
    branches:
      - master

env:
  DEBUG: ${{ vars.DEBUG }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BWS_ACCESS_TOKEN }}
          secrets: |
            7f42da1c-25ae-497a-89de-b041013fa10a > TG_TOKEN
            0a25642b-b877-4415-962b-b041013fb276 > TG_GROUP
            bc6f96c0-c7a9-4273-bac0-b041013fc1fa > TG_ALLOWEDUSERNAMES
            fd77264c-5755-497f-a2d0-b262017dde4b > TG_ALLOWEDCHATS
            627efa5d-6fdb-48bd-8956-b041013fcdab > WEATHERAPI_KEY
            3cdeba53-2ee5-49c6-9956-b041013fe498 > CURRENCYAPI_KEY
            645021f0-b0eb-41af-9aa9-b041013ff1a5 > OPENAIAPI_KEY
            457ec119-e932-4cbd-8ad2-b0ef00e47798 > MINIFLUXAPI_KEY
            0d11a328-87b9-4ade-837b-b0ef00e4baff > DEEPLAPI_KEY
            c9927e64-9dfb-49df-9dec-b1f50144f046 > TG_NOTIFICATION_BOT_TOKEN
            dfdace6a-de7f-4d62-b995-b1f5014bf00b > TG_NOTIFICATION_BOT_CHATID
            2af121a5-3856-4e27-9b65-b222006e7d15 > ANTHROPICAPI_KEY
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TARGET_HOST }}
          username: ${{ secrets.TARGET_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: TG_TOKEN,TG_GROUP,TG_ALLOWEDUSERNAMES,TG_ALLOWEDCHATS,WEATHERAPI_KEY,CURRENCYAPI_KEY,OPENAIAPI_KEY,MINIFLUXAPI_KEY,DEEPLAPI_KEY,ANTHROPICAPI_KEY,DEBUG
          script: |
            cd ~/familybot &&
            git fetch --all &&
            git reset --hard origin/master &&
            docker compose build --build-arg REVISION=$(git rev-parse --short master) &&
            docker compose up -d redis &&
            docker compose up -d --force-recreate familybot
      - name: send telegram notification
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TG_NOTIFICATION_BOT_CHATID }}
          token: ${{ env.TG_NOTIFICATION_BOT_TOKEN }}
          message: |
            🚀 Deployment Status: ${{ job.status }}
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Workflow: ${{ gitea.workflow }}
            Run: ${{ gitea.server_url }}/${{ gitea.repository }}/actions/runs/${{ gitea.run_number }}

            ${{ job.status == 'success' && '✅ Deployment completed successfully!' || '❌ Deployment failed!' }}
