name: build and deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - *.md
      - .gitignore

env:
  DEBUG: ${{ vars.DEBUG }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BWS_ACCESS_TOKEN }}
          secrets: |
            7f42da1c-25ae-497a-89de-b041013fa10a > TG_TOKEN
            dd565e5f-a287-4f5e-99f9-b35b015163c6 > TG_ADMINUSERIDS
            0a25642b-b877-4415-962b-b041013fb276 > TG_GROUPID
            627efa5d-6fdb-48bd-8956-b041013fcdab > WEATHERAPI_KEY
            3cdeba53-2ee5-49c6-9956-b041013fe498 > CURRENCYAPI_KEY
            645021f0-b0eb-41af-9aa9-b041013ff1a5 > OPENAIAPI_KEY
            457ec119-e932-4cbd-8ad2-b0ef00e47798 > MINIFLUXAPI_KEY
            0d11a328-87b9-4ade-837b-b0ef00e4baff > DEEPLAPI_KEY
            c9927e64-9dfb-49df-9dec-b1f50144f046 > TG_NOTIFICATION_BOT_TOKEN
            dfdace6a-de7f-4d62-b995-b1f5014bf00b > TG_NOTIFICATION_BOT_CHATID
            2af121a5-3856-4e27-9b65-b222006e7d15 > ANTHROPICAPI_KEY
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TARGET_HOST }}
          username: ${{ secrets.TARGET_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: TG_TOKEN,TG_GROUPID,TG_ADMINUSERIDS,WEATHERAPI_KEY,CURRENCYAPI_KEY,OPENAIAPI_KEY,DEEPLAPI_KEY,MINIFLUXAPI_KEY,ANTHROPICAPI_KEY,DEBUG
          script: |
            cd ~/familybot &&
            git fetch --all &&
            git reset --hard origin/master &&
            docker compose build --build-arg REVISION=$(git rev-parse --short master) &&
            docker compose up -d redis &&
            docker compose up -d --force-recreate familybot
      - name: send telegram notification
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TG_NOTIFICATION_BOT_CHATID }}
          token: ${{ env.TG_NOTIFICATION_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            *${{ gitea.workflow }}* workflow [run](${{ gitea.server_url }}/${{ gitea.repository }}/actions/runs/${{ gitea.run_number }}): ${{ job.status == 'success' && '✅' || '❌' }}
            repository: *${{ github.repository }}*
            branch: *${{ github.ref_name }}*
