name: build and deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BWS_ACCESS_TOKEN }}
          secrets: |
            7f42da1c-25ae-497a-89de-b041013fa10a > TELEGRAM_TOKEN
            0a25642b-b877-4415-962b-b041013fb276 > TELEGRAM_GROUP
            bc6f96c0-c7a9-4273-bac0-b041013fc1fa > TELEGRAM_ALLOWEDUSERNAMES
            627efa5d-6fdb-48bd-8956-b041013fcdab > WEATHERAPI_KEY
            3cdeba53-2ee5-49c6-9956-b041013fe498 > CURRENCYAPI_KEY
            645021f0-b0eb-41af-9aa9-b041013ff1a5 > OPENAIAPI_KEY
            457ec119-e932-4cbd-8ad2-b0ef00e47798 > MINIFLUXAPI_KEY
            0d11a328-87b9-4ade-837b-b0ef00e4baff > DEEPLAPI_KEY

      - name: Deploy
        env:
          DEBUG: ${{ github.event_name == 'push' && 'false' || github.event.inputs.debug }}
        run: |
          docker compose build --build-arg REVISION=$GITHUB_SHA
          docker compose up -d --force-recreate
