name: familybot

services:
  familybot:
    build: '..'
    container_name: familybot
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      - DEBUG
      - TZ=Europe/Helsinki
      - TELEGRAM_GROUP
      - TELEGRAM_ALLOWEDUSERNAMES
      - TELEGRAM_TOKEN
      - WEATHERAPI_KEY
      - CURRENCYAPI_KEY
      - OPENAIAPI_KEY
      - OPENAIAPI_GPTMODEL=gpt-4-1106-preview
      - MINIFLUXAPI_KEY
      - MINIFLUXAPI_BASEURL=https://miniflux.rahfar.com
      - MINIFLUXAPI_SITEURL=https://www.nytimes.com
      - DEEPLAPI_KEY
    restart: unless-stopped
    configs:
      - source: weatherapi_config.json
        target: /app/weatherapi_config.json

configs:
  weatherapi_config.json:
    file: ./configs/weatherapi_config.json
