name: familybot
services:
  familybot:
    image: ghcr.io/rahfar/familybot
    build: '..'
    container_name: familybot
    environment:
      - TZ=Europe/Helsinki
      - TELEGRAM_GROUP
      - TELEGRAM_ALLOWEDUSERNAMES
      - TELEGRAM_TOKEN
      - WEATHERAPI_KEY
      - WEATHERAPI_CITIES
      - CURRENCYAPI_KEY
      - OPENAIAPI_KEY
      - OPENAIAPI_GPTMODEL=gpt-4
    restart: unless-stopped
